project:
  type: book

book:
  title: "Introducción a la Construcción de Compiladores"
  author:
    - Alejandro Piad Morffis
    - Juan Pablo Consuegra Ayala
    - Rocío Cruz Linares
  chapters:
    - index.qmd
    - chap1.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap6.qmd
    - chap7.qmd
    - chap8.qmd

format:
  html:
    default: true
    theme: cosmo
    toc: true
  pdf:
    default: true
    documentclass: book
    classoption: [oneside]
    geometry:
      - margin=1in
    include-in-header: ../meta/header.tex

execute:
  enabled: false
